export const ALGORITHMIA_INSTRUCTIONS: Record<string, string[]> = {
  optimal_stopping: [
    'Revisa cada candidato uno por uno; el simulador te indica si es mejor que todos los anteriores.',
    'En cada candidato, decide entre "Detenerme aquí" o "Seguir viendo".',
    'Una vez que te detengas, presiona "Ver la comparación contra otras estrategias →" para ver cómo te fue frente a otras reglas.',
    'Escribe tu reflexión y presiona "Guardar respuesta" (o "Actualizar respuesta" si ya la habías guardado).',
  ],
  explore_exploit: [
    'Elige una opción por ronda haciendo clic en uno de los botones (Opción A, B, C...); cada clic gasta una ronda.',
    'Observa el contador de intentos y aciertos de cada opción para decidir si seguir probando o quedarte con la que mejor te resultó.',
    'Cuando se acaben las rondas, presiona "Ver la comparación contra otras estrategias →" para comparar tu resultado.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  sorting_cost: [
    'Mueve el control deslizante "Tamaño de la colección" para cambiar cuántos ítems tiene la lista.',
    'Mueve el control deslizante "¿Cuántas veces vas a buscar en ella?" para ajustar la cantidad de búsquedas.',
    'Observa cómo cambian las barras de costo de "Ordenar primero, después buscar" frente a "Buscar sin ordenar, siempre" y el punto de equilibrio indicado.',
    'Escribe tu reflexión y presiona "Guardar respuesta" cuando termines de explorar distintos valores.',
  ],
  cache_lru: [
    'Presiona "Atender pedido" para procesar el ítem solicitado y ver si fue acierto o no.',
    'Cuando la caché esté llena, haz clic en el ítem que quieres sacar para hacerle lugar al nuevo pedido.',
    'Al terminar todos los pedidos, presiona "Ver la comparación contra LRU puro y azar puro →" para comparar tu estrategia.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  scheduling: [
    'Usa las flechas de subir y bajar junto a cada tarea para reordenar la lista de pendientes (la primera es la que haces primero).',
    'Observa cómo cambia el "arrepentimiento total" (retraso acumulado) según el orden que armes.',
    'Presiona "Ver la comparación contra otras estrategias →" para comparar tu orden con otras estrategias de programación de tareas.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  bayes: [
    'Lee la descripción del escenario y escribe tu estimación numérica en el campo de texto.',
    'Presiona "Ver la regla" para revelar cuánto predice la regla estadística y comparar con tu número.',
    'Presiona "Siguiente escenario" (o "Terminar" en el último) para pasar al siguiente caso.',
    'Al terminar todos los escenarios, escribe tu reflexión y presiona "Guardar respuesta".',
  ],
  overfitting: [
    'Para cada ejemplo, elige "Está sobreajustado" o "Es generalizable" haciendo clic en el botón correspondiente.',
    'Responde todos los ejemplos de la lista antes de continuar.',
    'Presiona "Revisar respuestas" para ver cuáles acertaste y leer la explicación de cada caso.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  relaxation: [
    'Escribe en el campo de texto el objetivo que se siente imposible de planear.',
    'Elige una opción con los botones de radio para decidir qué restricción se relaja primero.',
    'Describe en el cuadro de texto cuál sería un primer paso concreto si esa restricción no existiera.',
    'Escribe tu reflexión final y presiona "Guardar respuesta" (los cuatro campos son obligatorios para poder guardar).',
  ],
  randomness: [
    'Haz clic en una de las barras del terreno para elegir tu punto de partida.',
    'Observa dónde termina la búsqueda: si llegó al mejor punto de todo el terreno o se quedó atascada en uno menor.',
    'Presiona "Ver qué pasa agregando algo de aleatoriedad →" para comparar la estrategia determinista contra una con aleatoriedad.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  backoff: [
    'Mueve el control deslizante para cambiar qué tan rápido crece la espera entre intentos (el multiplicador).',
    'Revisa cómo cambia tu calendario de seguimiento (cuántos días esperar en cada intento) según el valor elegido.',
    'Prueba con el multiplicador en ×1 (espera constante) y compáralo con valores más altos.',
    'Escribe tu reflexión y presiona "Guardar respuesta" cuando termines de explorar.',
  ],
  game_theory: [
    'Haz clic en una casilla del tablero 2x2 para apostar cuál combinación crees que sería el resultado.',
    'Presiona "Revelar el tablero" para ver los puntajes completos y si tu apuesta era un equilibrio.',
    'Compara tu casilla con la marcada en verde (el equilibrio real) y con el mejor resultado conjunto señalado.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  recursion: [
    'Presiona el botón "Llamar con n-1" varias veces para bajar la cadena de llamadas hasta encontrar el caso base.',
    'Cuando se te pregunte, elige si hay que "Seguir llamando con n-1" o "Detenerse: este es el caso base".',
    'En la fase de subida, escribe tu respuesta numérica y presiona "Revelar" para comparar con el valor real, luego presiona "Siguiente" para continuar.',
    'Al terminar de deshacer toda la cadena, escribe tu reflexión y presiona "Guardar respuesta".',
  ],
  tree_search: [
    'Presiona "Subir un nivel" para cada persona (hay un botón con el nombre de cada una) hasta que los dos caminos se encuentren en un ancestro común.',
    'Fíjate en qué generación quedan resaltados los dos caminos mientras subes.',
    'Cuando encuentres el ancestro común, presiona "Ver la comparación" para ver la diferencia entre un árbol balanceado y uno desbalanceado.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  graph_search: [
    'En la primera parte, haz clic en los nombres de los conocidos para construir un camino hasta la persona objetivo.',
    'Presiona "Siguiente: ruta más barata" para pasar al mapa de ciudades.',
    'En el mapa, haz clic en las conexiones (cada botón muestra su costo con "+n") para armar la ruta más barata hasta la ciudad destino.',
    'Compara tu camino y tu costo total con el mínimo posible que se muestra al llegar, y presiona "Terminar".',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  knapsack_dp: [
    'Marca las casillas de los ítems que quieras llevar, sin superar la capacidad disponible que se muestra arriba.',
    'Presiona "Confirmar mi selección" cuando tengas tu combinación lista (el botón se habilita solo si no te pasaste de la capacidad).',
    'Compara el valor de tu selección contra la mejor combinación posible y cuántas combinaciones revisó cada método.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  sorting_algorithms: [
    'Haz clic en el número que creas que es el menor de los que quedan por ordenar.',
    'Si te equivocas, lee el mensaje de aviso e inténtalo de nuevo con otro número.',
    'Repite hasta ordenar toda la lista; fíjate en cuántas comparaciones hiciste en total.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  hash_table: [
    'Para cada clave que aparece, haz clic en el botón "Casilla" donde creas que la ubica la función de hash.',
    'Si te equivocas, lee el mensaje de aviso, vuelve a calcular y elige otra casilla.',
    'Repite hasta colocar todas las claves; observa cuántas colocaste bien y compara los pasos de búsqueda de la hash table contra una lista sin indexar.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  greedy_activity_selection: [
    'Haz clic en cada actividad que quieras incluir; las que se traslapan con tu selección quedan deshabilitadas automáticamente.',
    'Junta la mayor cantidad posible de actividades sin conflictos de horario.',
    'Presiona "Confirmar mi selección" para comparar tu cantidad contra el máximo posible.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
  knn: [
    'Haz clic en una de las categorías para elegir tu predicción del caso nuevo.',
    'Presiona "Ver los vecinos más cercanos" para revelar los k vecinos más parecidos y la categoría que predice k-NN.',
    'Compara tu respuesta con la predicción del algoritmo y revisa cuáles puntos quedaron resaltados como vecinos.',
    'Escribe tu reflexión y presiona "Guardar respuesta" para terminar.',
  ],
};
